openapi: 3.0.3
info:
  title: Application Service API
  version: 1.0.0
  description: API для работы с заявками с лендинга
servers:
  - url: https://localhost:5000/api/v1
    description: Dev server
  - url: https://<domain>.ru/api/v1
    description: Production server

paths:
  /applications:
    post:
      summary: Создать заявку
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationCreate'
      responses:
        '201':
          description: Заявка создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '400':
          description: Ошибка валидации
        '429':
          description: Слишком много запросов
    get:
      summary: Получить список заявок (админ)
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          example: 1
        - in: query
          name: limit
          schema:
            type: integer
          example: 50
      responses:
        '200':
          description: Список заявок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
        '401':
          description: Не авторизован
        '403':
          description: Нет доступа

  /applications/{id}:
    patch:
      summary: Обновить статус заявки (админ)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationUpdate'
      responses:
        '200':
          description: Успешно обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '400':
          description: Некорректные данные
        '404':
          description: Заявка не найдена

    delete:
      summary: Удалить заявку (админ)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успешно удалено
        '404':
          description: Заявка не найдена

  /auth/login:
    post:
      summary: Авторизация
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Токен доступа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Неверные данные

components:
  schemas:
    Application:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        message:
          type: string
        status:
          type: string
          enum: [New, Processed]
        createdAt:
          type: string
          format: date-time
    ApplicationCreate:
      type: object
      required: [name, phone]
      properties:
        name:
          type: string
        phone:
          type: string
        message:
          type: string
    ApplicationUpdate:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [New, Processed]
    AuthRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        expiresIn:
          type: integer
